### ISSUE TITLE
Had to uninstall

### ISSUE THREAD

**Issue by ncottrill** [java-devil/OCDheim#14]
Hi, I love this mod, but I had to uninstall it because it was interferring with MassFarming's grid and I think other aspects of the cultivator (e.g. the PlantEverything mod destroy item with middle mouse button). 

Unfortunately, even after uninstalling OCDheim, I cannot remove the "align to world" aspect of the cultivator. I'm kind of sad. I'm not sure what to do.

You see, MassFarming is supposed to allow me to plant on a grid. The grid is supposed to line up with the plants I put down so that when I push the hotkey (shift) a chunk of plants would be planted. But, now, when I push the MassFarming hotkey, the planting aligns with the world grid (see image). I am unable to toggle this function (align with world) off.

![alignment-problem](https://user-images.githubusercontent.com/14022160/209502461-5c08da58-503f-427f-b7ac-9e741459c6e8.png)

**Comment by java-devil** [comment]
First of all - sad to see you go, you were my best "issuer".

As for the interference... Wasn't simply pressing LEFT-ALT to disable GRID MODE enough? The very first thing that OCDheim always does when you use the hoe / the cultivator is check if GRID MODE is enabled. If not - it doesn't do anything at all. If it helps - the next version of OCDheim will show an obnoxious visual cue when GRID MODE is enabled ;)

As for the behaviour post "deinstallation"... Are you 100% sure you removed the .dll file? OCDheim doesn't persist anything to disk, trust me on this one. It's virtually impossible for OCDheim to keep affecting Valheim in any way after the .dll is removed. But maybe MF somehow broke due to the interaction with OCDheim?

I would first try removeling these carrots and see if that helps. If not - I would try farming a completely fresh spot. If still not - I would completely reinstall MF.

Good Luck!

**Comment by ncottrill** [comment]
I installed and uninstalled mods all day yesterday. I'm stumped. Since I couldn't change the behavior no matter what I did, I reinstalled OCDHeim. The modpack we use is published on Thunderstore - its called GamingGroupies modpack by Jade. 

The LEFT-ALT disables GRID MODE in OCDHeim with the cultivator and block placement, but not in MassFarming. In MassFarming, the OCDHeim GRID MODE seems to stay active. MassFarming uses the SHIFT key to activate the grid planting. Does the SHIFT key have any function in OCDHeim?

**Comment by ncottrill** [comment]
Also, I don't see a configuration file in the server for OCDHeim. Is that expected behavior? I am used to being able to configure hotkeys and behavior in mods so that they will get along. :)

**Comment by ncottrill** [comment]
UPDATE:  This issue is a non-issue now. I figured out that when I want to rotate the MassFarming planting grid, I must do it without having the hotkey pressed down. This isn't in the documentation ... I just had to keep horsing around with it. So, I'm closing this as a "not OCDHeim issue" :)  Thanks again for writing this mod.
